/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Return aggregated dashboard data.
         */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description List reports with pagination.
         */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Report
         * @description Get the latest daily report.
         */
        get: operations["get_latest_report_api_reports_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Get a specific report by ID.
         */
        get: operations["get_report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Html
         * @description Get raw HTML content of a report.
         */
        get: operations["get_report_html_api_reports__report_id__html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Get aggregated performance summary.
         */
        get: operations["get_summary_api_performance_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendations
         * @description Get recommendations filtered by status.
         */
        get: operations["get_recommendations_api_performance_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sector Performance
         * @description Get per-sector performance breakdown.
         */
        get: operations["get_sector_performance_api_performance_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performance/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeseries
         * @description Get time series performance data.
         */
        get: operations["get_timeseries_api_performance_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrospective/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Weekly Analyses
         * @description List weekly analyses with pagination.
         */
        get: operations["list_weekly_analyses_api_retrospective_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrospective/weekly/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Analysis
         * @description Get a specific weekly analysis.
         */
        get: operations["get_weekly_analysis_api_retrospective_weekly__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrospective/daily-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Daily Checks
         * @description List recent daily retrospective checks.
         */
        get: operations["list_daily_checks_api_retrospective_daily_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Settings
         * @description Return current application settings.
         */
        get: operations["get_current_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Update settings by writing to .env file.
         *
         *     Only safe fields can be updated. Sensitive paths like
         *     claude_cli_path and database_url are not writable via API.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/test-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Email
         * @description Send a test email to verify SMTP config.
         */
        post: operations["test_email_api_settings_test_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check system health: DB, Claude CLI, SMTP.
         */
        get: operations["health_check_api_settings_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Pipeline
         * @description Trigger the daily report pipeline manually.
         */
        post: operations["trigger_pipeline_api_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Status
         * @description Return current pipeline status.
         */
        get: operations["get_pipeline_status_api_pipeline_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Debates
         * @description List recent debates, optionally filtered by pipeline.
         */
        get: operations["list_debates_api_debate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Generate a debate_id and acknowledge the trigger (stub).
         *
         *     The real debate is launched through the existing background runner used by
         *     ``POST /api/pipeline/run``. This endpoint is a thin shim that returns the
         *     would-be debate id and ``queued: true``. Full async-task launching is wired
         *     in Plan 4 alongside Multica integration; for now callers should still hit
         *     ``/api/pipeline/run`` to actually execute a pipeline.
         */
        post: operations["trigger_run_api_debate_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate/{debate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Debate
         * @description Return the full debate aggregate (rounds + verdict).
         */
        get: operations["get_debate_api_debate__debate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debate/{debate_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Debate
         * @description Stream live debate events as Server-Sent Events.
         */
        get: operations["stream_debate_api_debate__debate_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List every Role with its current binding, tools, and pipelines.
         */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Return a single role's binding + tools or 404 when unknown.
         */
        get: operations["get_agent_api_agents__role__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{role}/binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Binding
         * @description Persist a binding override for ``role``.
         */
        put: operations["put_binding_api_agents__role__binding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tree
         * @description Return the hierarchical memory tree (sector / date / strategy / patterns / lessons).
         */
        get: operations["get_tree_api_memory_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Keyword search across memory nodes via FTS5.
         */
        get: operations["search_api_memory_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read File
         * @description Return the raw markdown content of a memory file by relative path.
         */
        get: operations["read_file_api_memory_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BindingIn
         * @description Incoming binding override payload.
         */
        BindingIn: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** System Prompt Override */
            system_prompt_override?: string | null;
            /**
             * Timeout S
             * @default 600
             */
            timeout_s: number;
        };
        /**
         * DailyCheckOut
         * @description Daily retrospective check.
         */
        DailyCheckOut: {
            /** Id */
            id: number;
            /** Report Date */
            report_date: string;
            /** Recommendations Checked */
            recommendations_checked: number;
            /** Targets Hit */
            targets_hit: number;
            /** Stops Hit */
            stops_hit: number;
            /** Expired Count */
            expired_count: number;
        };
        /**
         * DashboardAlert
         * @description An alert for a recently closed recommendation.
         */
        DashboardAlert: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Pnl Percent */
            pnl_percent: number | null;
        };
        /**
         * DashboardOut
         * @description Aggregated dashboard data.
         */
        DashboardOut: {
            latest_report: components["schemas"]["LatestReportInfo"] | null;
            /** Open Recommendations */
            open_recommendations: number;
            /** Weekly Win Rate */
            weekly_win_rate: number;
            /** Weekly Closed */
            weekly_closed: number;
            /** Alerts */
            alerts: components["schemas"]["DashboardAlert"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LatestReportInfo
         * @description Summary info for the latest report.
         */
        LatestReportInfo: {
            /** Id */
            id: number;
            /** Date */
            date: string;
            /** Summary */
            summary: string;
        };
        /**
         * PerformanceSummary
         * @description Aggregated performance summary.
         */
        PerformanceSummary: {
            /** Total Recommendations */
            total_recommendations: number;
            /** Open Count */
            open_count: number;
            /** Target Hit Count */
            target_hit_count: number;
            /** Stop Hit Count */
            stop_hit_count: number;
            /** Expired Count */
            expired_count: number;
            /** Win Rate */
            win_rate: number;
            /** Avg Pnl */
            avg_pnl: number;
            /** Best Ticker */
            best_ticker: string;
            /** Best Pnl */
            best_pnl: number;
            /** Worst Ticker */
            worst_ticker: string;
            /** Worst Pnl */
            worst_pnl: number;
        };
        /**
         * PipelineRunResult
         * @description Result of pipeline trigger.
         */
        PipelineRunResult: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * PipelineStatusOut
         * @description Current pipeline status.
         */
        PipelineStatusOut: {
            /** Running */
            running: boolean;
            /** Last Result */
            last_result: string | null;
        };
        /**
         * RecommendationOut
         * @description Recommendation response model.
         */
        RecommendationOut: {
            /** Id */
            id: number;
            /** Report Id */
            report_id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Market */
            market: string;
            /** Direction */
            direction: string;
            /** Timeframe */
            timeframe: string;
            /** Entry Price */
            entry_price: number;
            /** Target Price */
            target_price: number;
            /** Stop Loss */
            stop_loss: number;
            /** Rationale */
            rationale: string;
            /** Sector */
            sector: string;
            /** Current Price */
            current_price: number | null;
            /** Status */
            status: string;
            /** Pnl Percent */
            pnl_percent: number | null;
            /** Closed At */
            closed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportDetailOut
         * @description Report detail with HTML content.
         */
        ReportDetailOut: {
            /** Id */
            id: number;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Report Type */
            report_type: string;
            /** Summary */
            summary: string;
            /** Generation Time S */
            generation_time_s: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Html Content */
            html_content: string;
        };
        /**
         * ReportOut
         * @description Report list item.
         */
        ReportOut: {
            /** Id */
            id: number;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Report Type */
            report_type: string;
            /** Summary */
            summary: string;
            /** Generation Time S */
            generation_time_s: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SectorPerformance
         * @description Per-sector performance.
         */
        SectorPerformance: {
            /** Sector */
            sector: string;
            /** Count */
            count: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
            /** Avg Return */
            avg_return: number;
        };
        /**
         * SettingsOut
         * @description Current settings (no secrets or sensitive paths).
         */
        SettingsOut: {
            /** Smtp Host */
            smtp_host: string;
            /** Smtp Port */
            smtp_port: number;
            /** Smtp User */
            smtp_user: string;
            /** Smtp Password Set */
            smtp_password_set: boolean;
            /** Email From */
            email_from: string;
            /** Email To */
            email_to: string[];
            /** Claude Model */
            claude_model: string;
            /** Report Language */
            report_language: string;
        };
        /**
         * SettingsUpdate
         * @description Partial settings update.
         *
         *     Only safe fields are writable. Sensitive paths like
         *     claude_cli_path and database_url cannot be changed via API.
         */
        SettingsUpdate: {
            /** Smtp Host */
            smtp_host?: string | null;
            /** Smtp Port */
            smtp_port?: number | null;
            /** Smtp User */
            smtp_user?: string | null;
            /** Smtp Password */
            smtp_password?: string | null;
            /** Email From */
            email_from?: string | null;
            /** Email To */
            email_to?: string[] | null;
            /** Claude Model */
            claude_model?: string | null;
            /** Report Language */
            report_language?: string | null;
        };
        /**
         * StatusOut
         * @description System health status.
         */
        StatusOut: {
            /** Database */
            database: boolean;
            /** Claude Cli */
            claude_cli: boolean;
            /** Smtp Configured */
            smtp_configured: boolean;
            /** All Ok */
            all_ok: boolean;
        };
        /**
         * TestEmailResult
         * @description Result of a test email.
         */
        TestEmailResult: {
            /** Success */
            success: boolean;
        };
        /**
         * TimeseriesPoint
         * @description Single time series data point.
         */
        TimeseriesPoint: {
            /** Date */
            date: string;
            /** Win Rate */
            win_rate: number;
            /** Cumulative Pnl */
            cumulative_pnl: number;
            /** Recommendations Count */
            recommendations_count: number;
        };
        /**
         * TriggerIn
         * @description Manual debate trigger payload.
         */
        TriggerIn: {
            /** Pipeline */
            pipeline: string;
        };
        /**
         * UpdateResult
         * @description Result of a settings update.
         */
        UpdateResult: {
            /** Updated */
            updated: string[];
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeeklyAnalysisDetailOut
         * @description Weekly analysis with full detail.
         */
        WeeklyAnalysisDetailOut: {
            /** Id */
            id: number;
            /** Week Start */
            week_start: string;
            /** Week End */
            week_end: string;
            /** Total Recommendations */
            total_recommendations: number;
            /** Win Count */
            win_count: number;
            /** Loss Count */
            loss_count: number;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pick Ticker */
            best_pick_ticker: string | null;
            /** Worst Pick Ticker */
            worst_pick_ticker: string | null;
            /** Analysis Text */
            analysis_text: string | null;
            /** Sector Breakdown */
            sector_breakdown: string | null;
            /** Lessons */
            lessons: string | null;
        };
        /**
         * WeeklyAnalysisOut
         * @description Weekly analysis summary.
         */
        WeeklyAnalysisOut: {
            /** Id */
            id: number;
            /** Week Start */
            week_start: string;
            /** Week End */
            week_end: string;
            /** Total Recommendations */
            total_recommendations: number;
            /** Win Count */
            win_count: number;
            /** Loss Count */
            loss_count: number;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pick Ticker */
            best_pick_ticker: string | null;
            /** Worst Pick Ticker */
            worst_pick_ticker: string | null;
            /** Analysis Text */
            analysis_text: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                report_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_report_api_reports_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetailOut"];
                };
            };
        };
    };
    get_report_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_html_api_reports__report_id__html_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_performance_summary_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_performance_recommendations_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sector_performance_api_performance_sectors_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorPerformance"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeseries_api_performance_timeseries_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weekly_analyses_api_retrospective_weekly_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAnalysisOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_analysis_api_retrospective_weekly__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAnalysisDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_checks_api_retrospective_daily_checks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCheckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_email_api_settings_test_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEmailResult"];
                };
            };
        };
    };
    health_check_api_settings_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
        };
    };
    trigger_pipeline_api_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResult"];
                };
            };
        };
    };
    get_pipeline_status_api_pipeline_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatusOut"];
                };
            };
        };
    };
    list_debates_api_debate_get: {
        parameters: {
            query?: {
                pipeline?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_api_debate_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_debate_api_debate__debate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_debate_api_debate__debate_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_agent_api_agents__role__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_binding_api_agents__role__binding_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_api_memory_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_memory_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_api_memory_file_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
