#!/usr/bin/env bash
#
# Multica self-host stack orchestration for daily-scheduler.
#
# Brings the Multica council operations console (postgres + backend + web) up
# and down via docker compose, so that `make dev` can stand up the whole stack
# with a single command. Subcommands:
#
#   up        Ensure Docker is running, start the stack, wait for health (hard
#             fail on error — used by `make multica-up`).
#   up-soft   Same as `up`, but never fails the caller. Logs a warning and
#             returns 0 when Docker is unavailable — used by `make dev` so a
#             missing Docker daemon does not block the native dev servers.
#   stop      Stop the containers but keep them and the data volumes (fast
#             restart, no data loss). Used by the `make dev` Ctrl+C trap.
#   down      Stop and remove the containers (named data volumes are kept).
#   status    Show container status and probe the backend health endpoint.
#   logs      Tail the stack logs.
#   wait      Block until the backend health endpoint responds (or timeout).
#
# Secrets live in .multica/.env (gitignored). When that file is missing — e.g.
# on a fresh clone — `up`/`up-soft` bootstrap it with freshly generated
# secrets so the stack still starts on the first `make dev`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$ROOT/docker-compose.multica.yml"
ENV_DIR="$ROOT/.multica"
ENV_FILE="$ENV_DIR/.env"

# How long to wait (seconds) for the Docker daemon and the backend health probe.
DOCKER_WAIT_TIMEOUT="${MULTICA_DOCKER_WAIT_TIMEOUT:-90}"
HEALTH_WAIT_TIMEOUT="${MULTICA_HEALTH_WAIT_TIMEOUT:-90}"

log()  { printf '  \033[36m[multica]\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m[multica]\033[0m %s\n' "$*" >&2; }
err()  { printf '  \033[31m[multica]\033[0m %s\n' "$*" >&2; }

# Backend port published on the host (defaults to 8080; honours an override in
# .multica/.env so the health probe always targets the right port).
backend_port() {
  if [ -f "$ENV_FILE" ]; then
    local p
    p="$(grep -E '^BACKEND_PORT=' "$ENV_FILE" | tail -1 | cut -d= -f2 | tr -d '[:space:]' || true)"
    [ -n "$p" ] && { printf '%s' "$p"; return; }
  fi
  printf '8080'
}

health_url() { printf 'http://localhost:%s/healthz' "$(backend_port)"; }

compose() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

# Generate .multica/.env with random secrets when it does not exist. Only the
# daily-scheduler-specific shape is written (ports 3001/8080, host webhook). A
# pre-existing file is never overwritten, so established Postgres credentials
# (tied to the data volume) are preserved.
ensure_env_file() {
  if [ -f "$ENV_FILE" ]; then
    return 0
  fi
  log "No .multica/.env found — generating one with fresh secrets…"
  mkdir -p "$ENV_DIR"
  local jwt pgpass
  jwt="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  pgpass="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > "$ENV_FILE" <<EOF
# Multica self-host — auto-generated by scripts/multica.sh
JWT_SECRET=$jwt
POSTGRES_DB=multica
POSTGRES_USER=multica
POSTGRES_PASSWORD=$pgpass
# daily-scheduler frontend already uses 3000 -> move Multica web to 3001
FRONTEND_PORT=3001
BACKEND_PORT=8080
APP_ENV=production
ALLOW_SIGNUP=true
MULTICA_APP_URL=http://localhost:3001
FRONTEND_ORIGIN=http://localhost:3001
EOF
  chmod 600 "$ENV_FILE"
  warn "Generated $ENV_FILE. To verify inbound webhooks, set MULTICA_WEBHOOK_SECRET"
  warn "in the root .env to this JWT_SECRET value."
}

# Return 0 when the Docker daemon is reachable.
docker_running() { docker info >/dev/null 2>&1; }

# Ensure the Docker daemon is up. On macOS, launch Docker Desktop and wait.
# Returns non-zero if the daemon is still unreachable after the timeout.
ensure_docker() {
  if docker_running; then
    return 0
  fi
  if [ "$(uname -s)" = "Darwin" ]; then
    log "Docker daemon not running — launching Docker Desktop…"
    open -a Docker >/dev/null 2>&1 || true
  else
    warn "Docker daemon not running. Start it (e.g. 'sudo systemctl start docker')."
  fi
  local waited=0
  while ! docker_running; do
    if [ "$waited" -ge "$DOCKER_WAIT_TIMEOUT" ]; then
      err "Docker daemon did not become ready within ${DOCKER_WAIT_TIMEOUT}s."
      return 1
    fi
    sleep 2
    waited=$((waited + 2))
  done
  log "Docker daemon is ready."
  return 0
}

# Poll the backend health endpoint until it responds 200 or the timeout hits.
wait_for_health() {
  local url waited=0
  url="$(health_url)"
  log "Waiting for Multica backend at $url …"
  while true; do
    if curl -fsS -o /dev/null --max-time 4 "$url" 2>/dev/null; then
      log "Multica backend is healthy."
      return 0
    fi
    if [ "$waited" -ge "$HEALTH_WAIT_TIMEOUT" ]; then
      err "Multica backend did not become healthy within ${HEALTH_WAIT_TIMEOUT}s."
      return 1
    fi
    sleep 3
    waited=$((waited + 3))
  done
}

print_urls() {
  log "Multica board UI : http://localhost:3001"
  log "Multica backend  : $(health_url)"
  log "Embedded view    : http://localhost:3000/multica"
}

cmd_up() {
  local soft="${1:-hard}"
  if ! ensure_docker; then
    if [ "$soft" = "soft" ]; then
      warn "Skipping Multica startup (Docker unavailable). Native dev servers will still run."
      warn "Start it later with: make multica-up"
      return 0
    fi
    return 1
  fi
  ensure_env_file
  log "Starting Multica stack (docker compose up -d)…"
  if ! compose up -d; then
    if [ "$soft" = "soft" ]; then
      warn "docker compose up failed — continuing without Multica."
      return 0
    fi
    return 1
  fi
  if ! wait_for_health; then
    if [ "$soft" = "soft" ]; then
      warn "Multica is starting but not healthy yet; check 'make multica-status'."
      return 0
    fi
    return 1
  fi
  print_urls
}

cmd_stop() {
  if ! docker_running; then
    warn "Docker not running — nothing to stop."
    return 0
  fi
  log "Stopping Multica stack (containers kept, data preserved)…"
  compose stop || true
}

cmd_down() {
  if ! docker_running; then
    warn "Docker not running — nothing to remove."
    return 0
  fi
  log "Removing Multica containers (data volumes preserved)…"
  compose down || true
}

cmd_status() {
  if ! docker_running; then
    warn "Docker daemon not running."
    return 0
  fi
  compose ps || true
  local url
  url="$(health_url)"
  if curl -fsS -o /dev/null --max-time 4 "$url" 2>/dev/null; then
    log "Health: UP ($url)"
  else
    warn "Health: DOWN ($url)"
  fi
}

cmd_logs() {
  compose logs -f
}

main() {
  case "${1:-}" in
    up)       cmd_up hard ;;
    up-soft)  cmd_up soft ;;
    stop)     cmd_stop ;;
    down)     cmd_down ;;
    status)   cmd_status ;;
    logs)     cmd_logs ;;
    wait)     wait_for_health ;;
    *)
      err "Usage: $0 {up|up-soft|stop|down|status|logs|wait}"
      exit 2
      ;;
  esac
}

main "$@"
